- name: CREATE VM PLAYBOOK SIMPLE
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # vmname: josetestansible03
   
  tasks:
  - name: Create simple VM
    azure_rm_virtualmachine:
      resource_group: ResGroupRH01
      name: testvm10
      vm_size: Standard_D1
      admin_username: jzl2w8
      admin_password: B1ue.red.fish
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest
